### ISSUE TITLE
DPCNN preactivation

### ISSUE THREAD

**Issue by HaishuoFang** [miracleyoo/DPCNN-TextCNN-Pytorch-Inception#1]
原文中好像是先进行了激活再卷积的吧，如果我没有理解错的话，您这个代码是卷积后再激活的吗？

**Comment by miracleyoo** [comment]
请问能具体指明一下哪个模型的哪个代码段吗？如果check确实有误，会及时订正的。

**Comment by HaishuoFang** [comment]
https://github.com/miracleyoo/DPCNN-TextCNN-Pytorch-Inception/blob/deaf766dcabf475e98914003c010a9c78e9158be/models/TextCNNDeep.py#L68-L70
原文不是先activation再进行的conv吗？

**Comment by DeligientSloth** [comment]
> 请问能具体指明一下哪个模型的哪个代码段吗？如果check确实有误，会及时订正的。

这里确实是先BN+activation再进行卷积的，主要是参考何恺明在resnet之后的结构上的改进，这样效果更好

**Comment by DeligientSloth** [comment]
> 请问能具体指明一下哪个模型的哪个代码段吗？如果check确实有误，会及时订正的。

 question_convs = [nn.Sequential(
            nn.Conv1d(in_channels=embed_size,
                      out_channels=self.channel_size,
                      kernel_size=kernel_size),
            nn.BatchNorm1d(self.channel_size),
            nn.ReLU(inplace=True),

            nn.Conv1d(in_channels=self.channel_size,
                      out_channels=self.channel_size,
                      kernel_size=kernel_size),
            nn.BatchNorm1d(self.channel_size),
            nn.ReLU(inplace=True),
            nn.MaxPool1d(kernel_size=(self.channel_size - kernel_size * 2 + 2))
        ) for kernel_size in opt.KERNEL_SIZE]
而且论文前面生成region_embedding的时候应该是没有maxpool的，何况你这个maxpool把整个句子都压缩完了，应该是在后面逐渐增大卷积视野的

**Comment by DeligientSloth** [comment]
这里有一份我改的代码，你看看，我觉得把conv那些定义在__init__里面好点，你这个是在forward里面定义的，我不熟悉torch，因为理论上forward会执行多次，每次执行的是不是同一个conv我不知道，所以我都定义在__init__里面，另外采用这种block的写法要好动点
class ResnetBlock(nn.Module):
    def __init__(self, channel_size):
        super(ResnetBlock, self).__init__()
        
        self.channel_size = channel_size
        self.maxpool = nn.Sequential(
            nn.ConstantPad1d(padding=(0, 1), value=0),
            nn.MaxPool1d(kernel_size=3, stride=2)
        )
        self.conv = nn.Sequential(
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),

            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
        )
    def forward(self, x):

        x_shortcut = self.maxpool(x)
        x = self.conv(x_shortcut)
        x = x + x_shortcut
#         print('resnet:{}'.format(x.shape))
        return x


class NeuralNet(nn.Module):
    """
    DPCNN model, 3
    1. region embedding: using TetxCNN to generte
    2. two 3 conv(padding) block
    3. maxpool->3 conv->3 conv with resnet block(padding) feature map: len/2
    """
    def __init__(self):
        super(NeuralNet, self).__init__()
        self.channel_size = 250

        self.embedding = nn.Embedding(max_features, embed_size)
        self.embedding.weight = nn.Parameter(torch.tensor(embedding_matrix, dtype=torch.float32))
        self.embedding.weight.requires_grad = False

        # region embedding
        self.region_embedding = nn.Sequential(
            nn.Conv1d(embed_size, self.channel_size, kernel_size=3, padding=1),
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Dropout(0.2)
        )
        self.conv_block = nn.Sequential(
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
        )
        
        self.seq_len = maxlen
        resnet_block_list = []
        while(self.seq_len > 2):
            resnet_block_list.append(ResnetBlock(self.channel_size))
            self.seq_len = self.seq_len//2
#         print('seqlen{}'.format(self.seq_len))
        self.resnet_layer = nn.Sequential(*resnet_block_list)
        
        self.linear_out = nn.Linear(self.seq_len * self.channel_size, 1)  # 改成输出一个值

    def forward(self, x):
        batch = x.shape[0]
        print("===========start==============")

        x = self.embedding(x)
        x = x.permute(0, 2, 1)
        x = self.region_embedding(x)
#         print(x.shape)

        x = self.conv_block(x)
#         print(x.shape)

        x = self.resnet_layer(x)
        
        x = x.permute(0, 2, 1)
#         print(x.shape)
#         print("===========end==============")
        x  = x.contiguous().view(x.size(0), -1)
        out = self.linear_out(x)
        return out

**Comment by DeligientSloth** [comment]
这里有一份我改的代码，你看看，我觉得把conv那些定义在__init__里面好点，你这个是在forward里面定义的，我不熟悉torch，因为理论上forward会执行多次，每次执行的是不是同一个conv我不知道，所以我都定义在__init__里面，另外采用这种block的写法要好动点
`
class ResnetBlock(nn.Module):
    def __init__(self, channel_size):
        super(ResnetBlock, self).__init__()
        
        self.channel_size = channel_size
        self.maxpool = nn.Sequential(
            nn.ConstantPad1d(padding=(0, 1), value=0),
            nn.MaxPool1d(kernel_size=3, stride=2)
        )
        self.conv = nn.Sequential(
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),

            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
        )
    def forward(self, x):

        x_shortcut = self.maxpool(x)
        x = self.conv(x_shortcut)
        x = x + x_shortcut
#         print('resnet:{}'.format(x.shape))
        return x


class NeuralNet(nn.Module):
    """
    DPCNN model, 3
    1. region embedding: using TetxCNN to generte
    2. two 3 conv(padding) block
    3. maxpool->3 conv->3 conv with resnet block(padding) feature map: len/2
    """
    def __init__(self):
        super(NeuralNet, self).__init__()
        self.channel_size = 250

        self.embedding = nn.Embedding(max_features, embed_size)
        self.embedding.weight = nn.Parameter(torch.tensor(embedding_matrix, dtype=torch.float32))
        self.embedding.weight.requires_grad = False

        # region embedding
        self.region_embedding = nn.Sequential(
            nn.Conv1d(embed_size, self.channel_size, kernel_size=3, padding=1),
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Dropout(0.2)
        )
        self.conv_block = nn.Sequential(
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
        )
        
        self.seq_len = maxlen
        resnet_block_list = []
        while(self.seq_len > 2):
            resnet_block_list.append(ResnetBlock(self.channel_size))
            self.seq_len = self.seq_len//2
#         print('seqlen{}'.format(self.seq_len))
        self.resnet_layer = nn.Sequential(*resnet_block_list)
        
        self.linear_out = nn.Linear(self.seq_len * self.channel_size, 1)  # 改成输出一个值

    def forward(self, x):
        batch = x.shape[0]
        print("===========start==============")

        x = self.embedding(x)
        x = x.permute(0, 2, 1)
        x = self.region_embedding(x)
#         print(x.shape)

        x = self.conv_block(x)
#         print(x.shape)

        x = self.resnet_layer(x)
        
        x = x.permute(0, 2, 1)
#         print(x.shape)
#         print("===========end==============")
        x  = x.contiguous().view(x.size(0), -1)
        out = self.linear_out(x)
        return out
`

**Comment by DeligientSloth** [comment]
这里有一份我改的代码，你看看，我觉得把conv那些定义在__init__里面好点，你这个是在forward里面定义的，我不熟悉torch，因为理论上forward会执行多次，每次执行的是不是同一个conv我不知道，所以我都定义在__init__里面，另外采用这种block的写法要好动点
`class ResnetBlock(nn.Module):
    def __init__(self, channel_size):
        super(ResnetBlock, self).__init__()

        self.channel_size = channel_size
        self.maxpool = nn.Sequential(
            nn.ConstantPad1d(padding=(0, 1), value=0),
            nn.MaxPool1d(kernel_size=3, stride=2)
        )
        self.conv = nn.Sequential(
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),

            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
        )

    def forward(self, x):
        x_shortcut = self.maxpool(x)
        x = self.conv(x_shortcut)
        x = x + x_shortcut
        #         print('resnet:{}'.format(x.shape))
        return x


class NeuralNet(nn.Module):
    """
    DPCNN model, 3
    1. region embedding: using TetxCNN to generte
    2. two 3 conv(padding) block
    3. maxpool->3 conv->3 conv with resnet block(padding) feature map: len/2
    """

    def __init__(self):
        super(NeuralNet, self).__init__()
        self.channel_size = 250

        self.embedding = nn.Embedding(max_features, embed_size)
        self.embedding.weight = nn.Parameter(torch.tensor(embedding_matrix, dtype=torch.float32))
        self.embedding.weight.requires_grad = False

        # region embedding
        self.region_embedding = nn.Sequential(
            nn.Conv1d(embed_size, self.channel_size, kernel_size=3, padding=1),
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Dropout(0.2)
        )
        self.conv_block = nn.Sequential(
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
            nn.BatchNorm1d(num_features=self.channel_size),
            nn.ReLU(),
            nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
        )

        self.seq_len = maxlen
        resnet_block_list = []
        while (self.seq_len > 2):
            resnet_block_list.append(ResnetBlock(self.channel_size))
            self.seq_len = self.seq_len // 2
        #         print('seqlen{}'.format(self.seq_len))
        self.resnet_layer = nn.Sequential(*resnet_block_list)

        self.linear_out = nn.Linear(self.seq_len * self.channel_size, 1)  # 改成输出一个值

    def forward(self, x):
        batch = x.shape[0]
        print("===========start==============")

        x = self.embedding(x)
        x = x.permute(0, 2, 1)
        x = self.region_embedding(x)
        #         print(x.shape)

        x = self.conv_block(x)
        #         print(x.shape)

        x = self.resnet_layer(x)

        x = x.permute(0, 2, 1)
        #         print(x.shape)
        #         print("===========end==============")
        x = x.contiguous().view(x.size(0), -1)
        out = self.linear_out(x)
        return out
`

**Comment by virgo777** [comment]
您加我QQ 5847713




------------------ 原始邮件 ------------------
发件人: "我是一只可爱的胖虎"<notifications@github.com>;
发送时间: 2018年12月24日(星期一) 中午1:59
收件人: "miracleyoo/DPCNN-TextCNN-Pytorch-Inception"<DPCNN-TextCNN-Pytorch-Inception@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [miracleyoo/DPCNN-TextCNN-Pytorch-Inception] DPCNN preactivation(#1)




这里有一份我改的代码，你看看，我觉得把conv那些定义在__init__里面好点，你这个是在forward里面定义的，我不熟悉torch，因为理论上forward会执行多次，每次执行的是不是同一个conv我不知道，所以我都定义在__init__里面，另外采用这种block的写法要好动点
 `class ResnetBlock(nn.Module):
 def init(self, channel_size):
 super(ResnetBlock, self).init()
     self.channel_size = channel_size     self.maxpool = nn.Sequential(         nn.ConstantPad1d(padding=(0, 1), value=0),         nn.MaxPool1d(kernel_size=3, stride=2)     )     self.conv = nn.Sequential(         nn.BatchNorm1d(num_features=self.channel_size),         nn.ReLU(),         nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),         nn.BatchNorm1d(num_features=self.channel_size),         nn.ReLU(),         nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),     ) def forward(self, x):     x_shortcut = self.maxpool(x)     x = self.conv(x_shortcut)     x = x + x_shortcut     #         print('resnet:{}'.format(x.shape))     return x  
class NeuralNet(nn.Module):
 """
 DPCNN model, 3
 1. region embedding: using TetxCNN to generte
 2. two 3 conv(padding) block
 3. maxpool->3 conv->3 conv with resnet block(padding) feature map: len/2
 """
 def __init__(self):     super(NeuralNet, self).__init__()     self.channel_size = 250     self.embedding = nn.Embedding(max_features, embed_size)     self.embedding.weight = nn.Parameter(torch.tensor(embedding_matrix, dtype=torch.float32))     self.embedding.weight.requires_grad = False     # region embedding     self.region_embedding = nn.Sequential(         nn.Conv1d(embed_size, self.channel_size, kernel_size=3, padding=1),         nn.BatchNorm1d(num_features=self.channel_size),         nn.ReLU(),         nn.Dropout(0.2)     )     self.conv_block = nn.Sequential(         nn.BatchNorm1d(num_features=self.channel_size),         nn.ReLU(),         nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),         nn.BatchNorm1d(num_features=self.channel_size),         nn.ReLU(),         nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),     )     self.seq_len = maxlen     resnet_block_list = []     while (self.seq_len > 2):         resnet_block_list.append(ResnetBlock(self.channel_size))         self.seq_len = self.seq_len // 2     #         print('seqlen{}'.format(self.seq_len))     self.resnet_layer = nn.Sequential(*resnet_block_list)     self.linear_out = nn.Linear(self.seq_len * self.channel_size, 1)  # 改成输出一个值 def forward(self, x):     batch = x.shape[0]     print("===========start==============")     x = self.embedding(x)     x = x.permute(0, 2, 1)     x = self.region_embedding(x)     #         print(x.shape)     x = self.conv_block(x)     #         print(x.shape)     x = self.resnet_layer(x)     x = x.permute(0, 2, 1)     #         print(x.shape)     #         print("===========end==============")     x = x.contiguous().view(x.size(0), -1)     out = self.linear_out(x)     return out  
`

**Comment by miracleyoo** [comment]
> 这里有一份我改的代码，你看看，我觉得把conv那些定义在__init__里面好点，你这个是在forward里面定义的，我不熟悉torch，因为理论上forward会执行多次，每次执行的是不是同一个conv我不知道，所以我都定义在__init__里面，另外采用这种block的写法要好动点
> `class ResnetBlock(nn.Module):
> def **init**(self, channel_size):
> super(ResnetBlock, self).**init**()
> 
> ```
>     self.channel_size = channel_size
>     self.maxpool = nn.Sequential(
>         nn.ConstantPad1d(padding=(0, 1), value=0),
>         nn.MaxPool1d(kernel_size=3, stride=2)
>     )
>     self.conv = nn.Sequential(
>         nn.BatchNorm1d(num_features=self.channel_size),
>         nn.ReLU(),
>         nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
> 
>         nn.BatchNorm1d(num_features=self.channel_size),
>         nn.ReLU(),
>         nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
>     )
> 
> def forward(self, x):
>     x_shortcut = self.maxpool(x)
>     x = self.conv(x_shortcut)
>     x = x + x_shortcut
>     #         print('resnet:{}'.format(x.shape))
>     return x
> ```
> class NeuralNet(nn.Module):
> """
> DPCNN model, 3
> 1. region embedding: using TetxCNN to generte
> 2. two 3 conv(padding) block
> 3. maxpool->3 conv->3 conv with resnet block(padding) feature map: len/2
> """
> 
> ```
> def __init__(self):
>     super(NeuralNet, self).__init__()
>     self.channel_size = 250
> 
>     self.embedding = nn.Embedding(max_features, embed_size)
>     self.embedding.weight = nn.Parameter(torch.tensor(embedding_matrix, dtype=torch.float32))
>     self.embedding.weight.requires_grad = False
> 
>     # region embedding
>     self.region_embedding = nn.Sequential(
>         nn.Conv1d(embed_size, self.channel_size, kernel_size=3, padding=1),
>         nn.BatchNorm1d(num_features=self.channel_size),
>         nn.ReLU(),
>         nn.Dropout(0.2)
>     )
>     self.conv_block = nn.Sequential(
>         nn.BatchNorm1d(num_features=self.channel_size),
>         nn.ReLU(),
>         nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
>         nn.BatchNorm1d(num_features=self.channel_size),
>         nn.ReLU(),
>         nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
>     )
> 
>     self.seq_len = maxlen
>     resnet_block_list = []
>     while (self.seq_len > 2):
>         resnet_block_list.append(ResnetBlock(self.channel_size))
>         self.seq_len = self.seq_len // 2
>     #         print('seqlen{}'.format(self.seq_len))
>     self.resnet_layer = nn.Sequential(*resnet_block_list)
> 
>     self.linear_out = nn.Linear(self.seq_len * self.channel_size, 1)  # 改成输出一个值
> 
> def forward(self, x):
>     batch = x.shape[0]
>     print("===========start==============")
> 
>     x = self.embedding(x)
>     x = x.permute(0, 2, 1)
>     x = self.region_embedding(x)
>     #         print(x.shape)
> 
>     x = self.conv_block(x)
>     #         print(x.shape)
> 
>     x = self.resnet_layer(x)
> 
>     x = x.permute(0, 2, 1)
>     #         print(x.shape)
>     #         print("===========end==============")
>     x = x.contiguous().view(x.size(0), -1)
>     out = self.linear_out(x)
>     return out
> ```
> `

好的！谢谢您的修改建议！我这两天会更新进去的😊

**Comment by miracleyoo** [comment]
已经做出了相应修改。如有进一步的问题请及时联系反馈，致谢！
另外，对于上面提出的一些问题，比如maxpool等，这个请注意您看的模型是TextCNN+DPCNN的结合模型。那一部分其实是TextCNN的操作而不是原文中的region embedding。DPCNN模型中则是按照@DeligientSloth 的写法构建的论文模型。十分感谢！

**Comment by DeligientSloth** [comment]
首先感谢回复！@DeligientSloth就是我。额，就是那一步虽然是TextCNN的，但是DPCNN是不包含textcnn的maxpool那一步的，只是生成了region embedding，不能机械地把textcnn照搬过来。因为maxpool的目的是聚合整个句子的语义特征，但是dpcnn显然是不需要的，后面还有很多个残差快叠加去感知整个句子，如果你前面就通过maxpool整合整个句子的话，后面的深层残差网络就没有意义了。

2018-12-27 

liliangde_sloth 



发件人：Miracleyoo <notifications@github.com>
发送时间：2018-12-27 12:25
主题：Re: [miracleyoo/DPCNN-TextCNN-Pytorch-Inception] DPCNN preactivation (#1)
收件人："miracleyoo/DPCNN-TextCNN-Pytorch-Inception"<DPCNN-TextCNN-Pytorch-Inception@noreply.github.com>
抄送："我是一只可爱的胖虎"<liliangde_sloth@163.com>,"Mention"<mention@noreply.github.com>

已经做出了相应修改。如有进一步的问题请及时联系反馈，致谢！
另外，对于上面提出的一些问题，比如maxpool等，这个请注意您看的模型是TextCNN+DPCNN的结合模型。那一部分其实是TextCNN的操作而不是原文中的region embedding。DPCNN模型中则是按照@DeligientSloth 的写法构建的论文模型。十分感谢！

**Comment by DeligientSloth** [comment]
https://github.com/DeligientSloth/TextClassification你可以去这里下一下，后续我会发更多模型

2018-12-27 

liliangde_sloth 



发件人：Nee <notifications@github.com>
发送时间：2018-12-26 09:24
主题：Re: [miracleyoo/DPCNN-TextCNN-Pytorch-Inception] DPCNN preactivation (#1)
收件人："miracleyoo/DPCNN-TextCNN-Pytorch-Inception"<DPCNN-TextCNN-Pytorch-Inception@noreply.github.com>
抄送："我是一只可爱的胖虎"<liliangde_sloth@163.com>,"Comment"<comment@noreply.github.com>

这里有一份我改的代码，你看看，我觉得把conv那些定义在__init__里面好点，你这个是在forward里面定义的，我不熟悉torch，因为理论上forward会执行多次，每次执行的是不是同一个conv我不知道，所以我都定义在__init__里面，另外采用这种block的写法要好动点
`class ResnetBlock(nn.Module):
def init(self, channel_size):
super(ResnetBlock, self).init()
    self.channel_size = channel_size
    self.maxpool = nn.Sequential(
        nn.ConstantPad1d(padding=(0, 1), value=0),
        nn.MaxPool1d(kernel_size=3, stride=2)
    )
    self.conv = nn.Sequential(
        nn.BatchNorm1d(num_features=self.channel_size),
        nn.ReLU(),
        nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),

        nn.BatchNorm1d(num_features=self.channel_size),
        nn.ReLU(),
        nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
    )

def forward(self, x):
    x_shortcut = self.maxpool(x)
    x = self.conv(x_shortcut)
    x = x + x_shortcut
    #         print('resnet:{}'.format(x.shape))
    return x

class NeuralNet(nn.Module):
"""
DPCNN model, 3
region embedding: using TetxCNN to generte 
two 3 conv(padding) block 
maxpool->3 conv->3 conv with resnet block(padding) feature map: len/2
""" 
def __init__(self):
    super(NeuralNet, self).__init__()
    self.channel_size = 250

    self.embedding = nn.Embedding(max_features, embed_size)
    self.embedding.weight = nn.Parameter(torch.tensor(embedding_matrix, dtype=torch.float32))
    self.embedding.weight.requires_grad = False

    # region embedding
    self.region_embedding = nn.Sequential(
        nn.Conv1d(embed_size, self.channel_size, kernel_size=3, padding=1),
        nn.BatchNorm1d(num_features=self.channel_size),
        nn.ReLU(),
        nn.Dropout(0.2)
    )
    self.conv_block = nn.Sequential(
        nn.BatchNorm1d(num_features=self.channel_size),
        nn.ReLU(),
        nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
        nn.BatchNorm1d(num_features=self.channel_size),
        nn.ReLU(),
        nn.Conv1d(self.channel_size, self.channel_size, kernel_size=3, padding=1),
    )

    self.seq_len = maxlen
    resnet_block_list = []
    while (self.seq_len > 2):
        resnet_block_list.append(ResnetBlock(self.channel_size))
        self.seq_len = self.seq_len // 2
    #         print('seqlen{}'.format(self.seq_len))
    self.resnet_layer = nn.Sequential(*resnet_block_list)

    self.linear_out = nn.Linear(self.seq_len * self.channel_size, 1)  # 改成输出一个值

def forward(self, x):
    batch = x.shape[0]
    print("===========start==============")

    x = self.embedding(x)
    x = x.permute(0, 2, 1)
    x = self.region_embedding(x)
    #         print(x.shape)

    x = self.conv_block(x)
    #         print(x.shape)

    x = self.resnet_layer(x)

    x = x.permute(0, 2, 1)
    #         print(x.shape)
    #         print("===========end==============")
    x = x.contiguous().view(x.size(0), -1)
    out = self.linear_out(x)
    return out

`
老哥能发一份完整代码么 跪求 nee_11235@qq.com
感谢

**Comment by LetheRiver** [comment]
您好，想请问一下我看到文章里说不对input的长度进行shortening or padding，但是我看到这个代码里好像是截取了定长的词序列作为输入？如果想要不截取定长而是用原始长度作为input要如何设计网络最后的fc层呢？谢谢！

**Comment by DeligientSloth** [comment]
不截取的情况下，关键是后面要跟几个resnet block，你可以试一下，DPCNN在我的任务上表现一般，我没用她了


| |
liliangde_sloth
|
|
liliangde_sloth@163.com
|
签名由网易邮箱大师定制
On 1/8/2019 18:35，LetheRiver<notifications@github.com> wrote：

您好，想请问一下我看到文章里说不对input的长度进行shortening or padding，但是我看到这个代码里好像是截取了定长的词序列作为输入？如果想要不截取定长而是用原始长度作为input要如何设计网络最后的fc层呢？谢谢！

**Comment by yanfan0531** [comment]
> 不截取的情况下，关键是后面要跟几个resnet block，你可以试一下，DPCNN在我的任务上表现一般，我没用她了 | | liliangde_sloth | | liliangde_sloth@163.com | 签名由网易邮箱大师定制 On 1/8/2019 18:35，LetheRiver<notifications@github.com> wrote： 您好，想请问一下我看到文章里说不对input的长度进行shortening or padding，但是我看到这个代码里好像是截取了定长的词序列作为输入？如果想要不截取定长而是用原始长度作为input要如何设计网络最后的fc层呢？谢谢！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

hi，能问下为什么在ResnetBlock里面，做max_pooling之前要先做padding嘛?
